# Regular Expressions
```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(knitr)
library(dplyr)

schedule <- read.csv("./data/example_schedule.csv", stringsAsFactors = FALSE)
unit_items <- schedule %>% filter(Unit == 1)
start_date <- format(as.Date(unit_items$Start), format = "%A, %B %d %Y")
end_date <- format(as.Date(unit_items$End), format = "%A, %B %d %Y")
due_date <- ifelse(!is.na(unit_items$Due.Date), format(as.Date(unit_items$Due.Date), format = "%A, %B %d %Y"), NA)
due_items_long <- gsub(", ", "  \n* ", unit_items$Due.Long)
span_message <- paste("<i>This unit spans <b>", start_date, " </b>through <b>", end_date, "</b>.</i>", sep="")
due_message <- paste("At 11:59 PM on", due_date, "the following items are due:")
head_message_items_due <- paste(span_message, "  \n<b>", due_message, "</b>  \n\n* ", due_items_long, sep="")
head_message_no_items_due <- paste(span_message, "  \n<b>There are no items due this unit.</b>", sep="")
head_message <- ifelse(!is.na(due_date), head_message_items_due, head_message_no_items_due)
```
`r head_message`

This unit reviews the course syllabus, expectations, and the tools we will be using throughout the semester. We'll also cover some of the more basic functions in R.

## Media

Some of the videos linked completely overlap the notes below, others don't have as much overlap. The notes will almost always be more comprehensive than the videos so I strongly recommend you start with the readings and read the notes first, then preview the videos. 

## Course Tools

In addition to the tools we used in [BAN 300](http://jamessuleiman.com/ban300/), which is a prerequisite to this course, we'll be using some private team features in slack and learning how to collaborate using Git and GitHub. You will be required to work in teams of two to three peopl for all assignments and your project.
